name: Vigilante de Pre√ßos üïµÔ∏è‚Äç‚ôÇÔ∏è

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:
  ronda:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o Codigo
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar arquivo
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python vigilante.py
